# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IP-32. Code for life.
email: ip32group@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Блог групи ІП-32, КПІ, ФІОТ.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://KPI-FICT-IP32.github.io" # the base hostname & protocol for your site
github_username:  KPI-FICT-IP32
github_repo: KPI-FICT-IP32.github.io

# Build settings
markdown: kramdown
